### ISSUE TITLE
Error on start when using Quick-Scope

### ISSUE THREAD

**Issue by XiaochenCui** [agude/eldar.vim#1]
```
Error detected while processing function <SNR>60_set_highlight_colors[37]..<SNR>60_add_to_highlight_group:
line    1:
E417: missing argument: ctermbg=
Error detected while processing function <SNR>60_set_highlight_colors[38]..<SNR>60_add_to_highlight_group:
line    1:
E417: missing argument: ctermbg=
Press ENTER or type command to continue
```
VIM - Vi IMproved 8.0
Ubuntu 14.04

**Comment by agude** [comment]
Thanks for the report @XiaochenCui. I'll try to reproduce this tonight. I haven't yet installed Vim8 (I'm mostly on Neovim now) so I'll need to do that first.

**Comment by agude** [comment]
Looks like this is related to [unblevable/quick-scope](https://github.com/unblevable/quick-scope). I'll try to debug further.

**Comment by agude** [comment]
It looks like this is [a bug in quickscope](https://github.com/unblevable/quick-scope/issues/33).

I installed quickscope and I only get the error when I load a color scheme with `cursorline` set. Is that the same for you?

**Comment by agude** [comment]
@XiaochenCui Please update and let me know if [this commit](https://github.com/agude/vim-eldar/commit/c0a005d4359ec07ec7efddc1b3bc069d4c2f77ff) fixed it. Thanks!

**Comment by XiaochenCui** [comment]
@agude I checked plugins installed, and there is quick-scope inside it. So it's not vim-eldar's problem.
Thanks for reply. :+1:

**Comment by XiaochenCui** [comment]
@agude Thanks you, problem solved after your new commit.
