### ISSUE TITLE
Able to change default color?

### ISSUE THREAD

**Issue by kanaanayt** [agude/eldar.vim#8]
The default color is tango. Is there the option to change that?

**Comment by agude** [comment]
Yes!

## If you are running in the terminal

Then the colors are the terminal colors. To change them you'll need to change the colors your terminal is using. Probably something like: `Edit > Preferences > Colors` (at least on Gnome Terminal).

## If you are running in the GUI

Then the colors are set by the script, and you can override them easily!

The script does this:

```vim
" GUI colors                                                                                                                            
let s:red       = get(g:, 'eldar_red', '#EF2929')                                                                                       
let s:yellow    = get(g:, 'eldar_yellow', '#FCE94F')                                                                                    
let s:green     = get(g:, 'eldar_green', '#8AE234')                                                                                     
let s:cyan      = get(g:, 'eldar_cyan', '#34E2E2')                                                                                      
let s:blue      = get(g:, 'eldar_blue', '#729FCF')                                                                                      
let s:magenta   = get(g:, 'eldar_magenta', '#AD7FA8')                                                                                   
let s:gui_text  = get(g:, 'eldar_text', 'White')                                                                                        
let s:gui_bg    = get(g:, 'eldar_background', 'Black')    
let s:term_text  = get(g:, 'eldar_term_text', 'NONE')
let s:term_bg    = get(g:, 'eldar_term_background', 'NONE')
```

Any color you want to override you can set in your `.vimrc` (or equivilent) like this:

```vim
" Override Eldar GUI colors
let g:eldar_red     = "#ff0000"
let g:eldar_yellow  = "#ffff00"
let g:eldar_green   = "#00ff00"
let g:eldar_cyan    = "#00ffff"
let g:eldar_blue    = "#0000ff"
let g:eldar_magenta = "#ff00ff"
```

Does that work for you?

**Comment by kanaanayt** [comment]
The function definitions are orange. But that doesn't appear in the script. Is that the case for you as well?

**Comment by kanaanayt** [comment]
Okay never mind. Found it!

**Comment by agude** [comment]
Did you get it working? Just to be sure, here is what you would put in your `.vimrc` if you wanted to use [sky blue](https://www.colorhexa.com/87ceeb) instead of the default blue:

```vim
let g:eldar_blue = "#87ceeb"
colorscheme eldar
```

It's important to change the color **before** setting the color scheme, because when the color scheme loads it will look for custom colors you set, but it won't find them if you define the colors after loading the scheme. :-)
