### ISSUE TITLE
Error messages when use the colorscheme on neovim

### ISSUE THREAD

**Issue by tan-wei** [agude/eldar.vim#9]
Both of terminal and GUI will show this error message, seems it does not compatible with `coc.nvim`
```
[coc.nvim] Error: call_atomic request error on "nvim_command": Vim(highlight):E421:Color name or number not recognized: ctermfg=NaN guifg=#00000E  
```

**Comment by agude** [comment]
That `ctermfg=NaN` has got to be the problem. Is this happening when launching coc, or taking some action? Not a coc user, but I'll try to set it up to reproduce.

**Comment by agude** [comment]
@tan-wei Can you capture the output of `:highlight` when you get the error?

You can save it to a file like so[1]:

```
:redir highlight.txt
:highlight
:redir END
```

And upload that to this report? Should make it easier to figure out which group is causing the issue.

[1]: Stolen from https://stackoverflow.com/a/16049993/1342354

**Comment by tan-wei** [comment]
OK:
[highlight.txt](https://github.com/agude/vim-eldar/files/8967865/highlight.txt)

**Comment by tan-wei** [comment]
> That `ctermfg=NaN` has got to be the problem. Is this happening when launching coc, or taking some action? Not a coc user, but I'll try to set it up to reproduce.

No any extra actions, but `:colorscheme eldar` manually can reproduce this.

**Comment by agude** [comment]
HI @tan-wei, thanks for your patience!

Finally started debugging and I can't reproduce in Docker:

```dockerfile
FROM ubuntu:22.04

RUN apt-get update && \
    apt-get install -y \
        curl \
        git \
        neovim \
        nodejs \
        npm \
    && \
    rm -rf /var/lib/apt/lists/*

# Install coc.nvim
RUN mkdir -p ~/.local/share/nvim/site/pack/coc/start && \
    cd ~/.local/share/nvim/site/pack/coc/start && \
    git clone --branch release https://github.com/neoclide/coc.nvim.git --depth=1 && \
    nvim -c "helptags coc.nvim/doc/ | q"

# Install eldar.vim
RUN curl https://raw.githubusercontent.com/agude/vim-eldar/master/colors/eldar.vim > /tmp/eldar.vim && \
    mkdir -p ~/.config/nvim/colors && \
    mv /tmp/eldar.vim ~/.config/nvim/colors
```

And then opening `nvim` and running `:colorscheme eldar`. It must be some coc extension. Can you let me know what you have installed and what your coc config is?

**Comment by tan-wei** [comment]
Thanks for spending too much time on it. The coc extension lists:
```vim
let g:coc_global_extensions = [
                              \ 'coc-json',
                              \ 'coc-git',
                              \ 'coc-markdown-preview-enhanced',
                              \ 'coc-spell-checker',
                              \ 'coc-lists',
                              \ 'coc-snippets',
                              \ 'coc-yank',
                              \ 'coc-explorer',
                              \ ]
```
And the complete configure file with my neovim is [here](https://github.com/tan-wei/neovim-init.vim).

**Comment by agude** [comment]
Success! I can reproduce!

Now on to debugging...

![Screenshot from 2022-07-17 10-02-00](https://user-images.githubusercontent.com/4562016/179416627-88e49747-fe3e-4af5-8725-1b3b4bb817b3.png)

**Comment by agude** [comment]
Ok, pretty sure these are the problem lines:

https://github.com/agude/vim-eldar/blob/master/colors/eldar.vim#L68

Specifically the `NONE` in term_text.

**Comment by tan-wei** [comment]
Great!

**Comment by agude** [comment]
Can you give the most recent commit a try? 70f681812d2201a44ab53e86df3f98f0d57e2ad0

There is some issue where if both `guifg` and `ctermfg` are set in the `Normal` highlight group then things go weird. So I only set `guifg` if using a GUI and `ctermfg` if in a terminal.

**Comment by tan-wei** [comment]
Great! Seems OK now. Thanks!!!
